name: Build and Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset: psmoveapi-4.0.12-linux.tar.gz
          - os: macos-13
            asset: psmoveapi-4.0.12-macos.tar.gz
          - os: windows-latest
            asset: psmoveapi-4.0.12-windows-msvc2017-x64.zip

    steps:
      - uses: actions/checkout@v4

      - name: Download psmoveapi prebuilt
        run: |
          curl -L -o psmoveapi.${{ matrix.asset }} https://github.com/thp/psmoveapi/releases/download/4.0.12/${{ matrix.asset }}

      - name: Extract psmoveapi (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p ${{ github.workspace }}/psmoveapi_install
          tar -xzf psmoveapi.${{ matrix.asset }} -C ${{ github.workspace }}/psmoveapi_install --strip-components=1

      - name: Extract psmoveapi (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p ${{ github.workspace }}\psmoveapi_install
          7z x psmoveapi.${{ matrix.asset }} -o${{ github.workspace }}\psmoveapi_install

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev libbluetooth-dev pkg-config

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install libusb pkg-config

      - name: Configure
        run: cmake -S . -B build -DPSMOVE_ROOT=${{ github.workspace }}/psmoveapi_install

      - name: Build
        run: cmake --build build --config Release -j 4

      - name: Determine release tag
        id: get_release
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            # fetch the latest release tag
            latest=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
            echo "tag=$latest" >> $GITHUB_OUTPUT
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/dsu_server_psmove${{ runner.os == 'Windows' && '.exe' || '' }}
          tag_name: ${{ steps.get_release.outputs.tag }}
